1
Internal error: 'with' clause failed unexpectedly in 'foo'
	0
	main_0_0
	foo_0_0
	with_1_1 <==
